### ISSUE TITLE
期待Python部分

### ISSUE THREAD

**Issue by cxgreat2014** [CHYbeta/Code-Audit-Challenges#1]
有支持/捐赠二维码吗？

**Comment by CHYbeta** [comment]
嘻，谢谢。python的部分会后续增加的。二维码就不贴啦，毕竟只是做了点微小的工作。如果有啥好的题目，欢迎提供：）

**Comment by cxgreat2014** [comment]
好的，谢谢您的工作~目前我正在做网页开发，第一道题目太冲击三观，已经想弃坑php了23333
另外，python好评

**Comment by CHYbeta** [comment]
hh挑战（Challenge）嘛。真实场景中一些太极端的情况是不会出现的。
